Repository Codium-ai/AlphaCodium, pull requests merged in 2024-02, with the labels that each got.

#28 Update requirements.txt to work on MacOS
  requirements.txt
Labels: enhancement, Review effort [1-5]: 1

#29 Missing reference to package settings under alpha_codium for get_settings() in 2 scripts
  alpha_codium/code_contests/eval/pass_at_k_evaluator.py
  alpha_codium/llm/token_handler.py
Labels: Review effort [1-5]: 1, Bug fix

#31 Update duckdb version to 0.9.2
  requirements.txt
Labels: enhancement, Review effort [1-5]: 1

#32 [Feature] solve a custom problem provided in a json file
  README.md
  alpha_codium/gen/coding_competitor.py
  alpha_codium/solve_my_problem.py
  my_problem_example.json
Labels: documentation, enhancement, Review effort [1-5]: 3

#25 Read frequency_penalty from configuration.toml and add it to all stages. The stages can still overwrite it.
  alpha_codium/gen/coding_competitor.py
  alpha_codium/settings/code_contests_prompts_choose_best_solution.toml
  alpha_codium/settings/code_contests_prompts_reflect.toml
  alpha_codium/settings/code_contests_prompts_validate_ai_tests.toml
  alpha_codium/settings/code_contests_prompts_validate_reflection.toml
  alpha_codium/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 2
