Repository Codium-ai/AlphaCodium, pull requests merged in 2024-01, with the labels that each got.

#5 Add Technical Q&A section to README.md
  README.md
  pics/comparison.png
  pics/computational_effort.png
Labels: documentation, Review effort [1-5]: 1

#6 Add Table of Contents to README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#7 q&a
  README.md
Labels: documentation, Review effort [1-5]: 1

#8 Update code_contests_prompts_generate_ai_tests.toml
  alpha_codium/settings/code_contests_prompts_generate_ai_tests.toml
Labels: enhancement, Review effort [1-5]: 1

#10 Optimized the estimator code_contests_metric.py
  alpha_codium/code_contests/eval/code_contests_metric.py
Labels: enhancement, Review effort [1-5]: 2

#15 Update README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#16 updates
  README.md
  alpha_codium/llm/ai_handler.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#18 Optimized and commented code
  alpha_codium/evaluate_dataset.py
Labels: enhancement, Review effort [1-5]: 2
